# Generated by Django 4.2.27 on 2026-04-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="contriber_name",
            new_name="contributer_name",
        ),
    ]
