# Generated by Django 4.2.23 on 2026-04-02 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0002_rename_contriber_name_picture_contributer_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joke", old_name="contributer_name", new_name="contributor_name",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="contributer_name",
            new_name="contributor_name",
        ),
    ]
