# Generated by Django 4.2.27 on 2026-03-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("registration_date", models.DateField()),
                ("party_affiliation", models.CharField(max_length=100)),
                ("precinct_number", models.CharField(max_length=20)),
                ("v20state", models.CharField(max_length=2)),
                ("v21town", models.CharField(max_length=100)),
                ("v21primary", models.CharField(max_length=100)),
                ("v22general", models.CharField(max_length=100)),
                ("v23town", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Residential_Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_number", models.CharField(max_length=20)),
                ("street_name", models.CharField(max_length=100)),
                ("apartment_number", models.CharField(blank=True, max_length=20)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residential_addresses",
                        to="voter_analytics.voter",
                    ),
                ),
            ],
        ),
    ]
