# Generated by Django 4.2.27 on 2026-03-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter", name="voter_score", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.BooleanField(default=False),
        ),
    ]
