# Generated by Django 4.2.27 on 2026-03-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_voter_voter_score_alter_voter_v20state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="voter_score",
            field=models.IntegerField(default=0),
        ),
    ]
