# Generated by Django 4.2.23 on 2026-04-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_project", "0002_customer_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer", name="image_url", field=models.URLField(blank=True),
        ),
    ]
