# Generated by Django 4.2.23 on 2026-04-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_project", "0003_customer_image_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="image_url",),
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="final_project/customers/"
            ),
        ),
    ]
