# Generated by Django 4.2.23 on 2026-04-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_project", "0005_restaurant_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="restaurant_owner",
            field=models.BooleanField(default=False),
        ),
    ]
