# Generated by Django 4.2.27 on 2026-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                ("profile_image_url", models.URLField(blank=True)),
                ("bio_text", models.TextField(blank=True)),
                ("join_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
