# Generated by Django 4.2.27 on 2026-02-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="photo", name="image_url", field=models.URLField(blank=True),
        ),
    ]
