# Generated by Django 4.2.27 on 2026-02-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_photo_image_file_alter_photo_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
